<a href="https://colab.research.google.com/github/Rominaarab/teaching/blob/main/Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch torchvision torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 39.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 29.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 67.8 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

craet some metrics

In [ ]:
#3*3
w = [[1, 1, 1,],
     [1.5, 1.5, 1.5],
     [2, 2, 2,]]

#3*1
x = [[6], [7], [8]]

b = [[1], [1], [1]]

y = [[0], [0], [0]]

In [ ]:
#transform to numpy array:
w_np = np.array(w)

x_np = np.array(x)

#creat an array of one
b_np = np.ones((3, 1))

output = np.matmul(w_np, x_np)+b_np

print(output)
print(output.shape)

[[22. ]
 [32.5]
 [43. ]]
(3, 1)


In [ ]:
w_torch = torch.FloatTensor(w)

x_torch = torch.FloatTensor(x)

b_torch = torch.ones((3, 1))

output_torch = torch.matmul(w_torch, x_torch)+b_torch

print(output_torch)
print(output.shape)

tensor([[22.0000],
        [32.5000],
        [43.0000]])
(3, 1)


In [ ]:
#creat a random numpy array:
np_array = np.random.random((3, 4))
print(np_array)

[[0.44364632 0.56813839 0.99053479 0.31098875]
 [0.36399301 0.72289447 0.81473212 0.58845203]
 [0.36846067 0.99692496 0.90993394 0.74264923]]


In [ ]:
#covert to torch
torch_tensor = torch.FloatTensor(np_array)
print(torch_tensor)

tensor([[0.4436, 0.5681, 0.9905, 0.3110],
        [0.3640, 0.7229, 0.8147, 0.5885],
        [0.3685, 0.9969, 0.9099, 0.7426]])


In [ ]:
#convert back to np
np_array_2 = torch_tensor.numpy()
print(np_array_2)

[[0.4436463  0.56813836 0.9905348  0.31098875]
 [0.36399302 0.7228945  0.81473213 0.58845204]
 [0.36846066 0.99692494 0.9099339  0.74264926]]


In [ ]:
#creat a 2d tensor
y = torch.rand(4, 5)

#this will craet a vectors of number from 0-1
print(y)

tensor([[0.6080, 0.2948, 0.3852, 0.0246, 0.6554],
        [0.4564, 0.0276, 0.8511, 0.2197, 0.8276],
        [0.5709, 0.3513, 0.2461, 0.4763, 0.2819],
        [0.7074, 0.3276, 0.1219, 0.9345, 0.2096]])


In [ ]:
#we can perform normal python scalar on torch
print(y * 10)

print((y + 1)**2)

print(y + y)

print(y/(y + 1))


#combination of torch function and normal python arithmetic
print(torch.sqrt(y**2))

tensor([[6.0805, 2.9478, 3.8522, 0.2465, 6.5545],
        [4.5640, 0.2761, 8.5113, 2.1969, 8.2761],
        [5.7092, 3.5131, 2.4607, 4.7630, 2.8190],
        [7.0739, 3.2759, 1.2188, 9.3450, 2.0964]])
tensor([[2.5858, 1.6765, 1.9188, 1.0499, 2.7405],
        [2.1211, 1.0560, 3.4267, 1.4876, 3.3402],
        [2.4678, 1.8260, 1.5527, 2.1795, 1.6433],
        [2.9152, 1.7625, 1.2586, 3.7423, 1.4632]])
tensor([[1.2161, 0.5896, 0.7704, 0.0493, 1.3109],
        [0.9128, 0.0552, 1.7023, 0.4394, 1.6552],
        [1.1418, 0.7026, 0.4921, 0.9526, 0.5638],
        [1.4148, 0.6552, 0.2438, 1.8690, 0.4193]])
tensor([[0.3781, 0.2277, 0.2781, 0.0241, 0.3959],
        [0.3134, 0.0269, 0.4598, 0.1801, 0.4528],
        [0.3634, 0.2600, 0.1975, 0.3226, 0.2199],
        [0.4143, 0.2468, 0.1086, 0.4831, 0.1733]])
tensor([[0.6080, 0.2948, 0.3852, 0.0246, 0.6554],
        [0.4564, 0.0276, 0.8511, 0.2197, 0.8276],
        [0.5709, 0.3513, 0.2461, 0.4763, 0.2819],
        [0.7074, 0.3276, 0.1219, 0.9345, 0.209

In [ ]:
print(y.min(), y.max(), y.std(), y.sum() )

tensor(0.0246) tensor(0.9345) tensor(0.2694) tensor(8.5781)


In [ ]:
#creat two 3D tensor
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)

print(tensor_1 + tensor_2)

tensor([[[0.8707, 0.3004, 0.8063],
         [0.2589, 0.8501, 1.2649],
         [1.7214, 1.6098, 1.0586]],

        [[1.3927, 1.4259, 0.7687],
         [0.2749, 0.8625, 1.0427],
         [1.5771, 1.0875, 0.5040]],

        [[0.8407, 1.0081, 1.6085],
         [1.2031, 0.7351, 0.9374],
         [1.1030, 1.5762, 0.3251]]])


In [ ]:
print(torch.bmm(tensor_1, tensor_2))

tensor([[[0.1942, 0.1380, 0.1301],
         [0.7206, 0.7703, 0.2064],
         [1.5936, 1.5325, 1.1419]],

        [[1.1104, 1.4740, 0.4051],
         [0.5767, 0.7732, 0.2175],
         [0.9842, 1.1284, 0.1503]],

        [[0.7297, 1.2290, 0.7927],
         [0.5140, 0.4776, 0.7248],
         [0.9185, 0.7656, 1.2483]]])
